
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: main.yaml
  namespace: argocd
spec:
  ignoreDifferences:
    - group: argoproj.io
      kind: Application
      jsonPointers:
        - /operation
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
  project: default
  sources:
    - repoURL: 'https://github.com/ThomasHelmCharts/argocd-applications'
      path: ./
      targetRevision: "HEAD" 
      helm:
        valueFiles:
          - values.yaml
          - $templates/homepage/homepage.yaml
          - $templates/kube-ops-view/kube-ops-view.yaml
          - $templates/metrics-server/metrics-server.yaml
        valuesObject:
          domain: &domain .kind.localhost
          apps_values:
            git@github.com/ThomasInfras/argocd-template/homepage/homepage:
              domain: *domain
            git@github.com/ThomasInfras/argocd-template/kube-ops-view/kube-ops-view:
              domain: *domain              
    - repoURL: 'https://github.com/ThomasInfras/argocd-templates'
      targetRevision: "HEAD"
      ref: templates
