
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: main.yaml
  namespace: argocd
spec:
  ignoreDifferences:
    - group: argoproj.io
      kind: Application
      jsonPointers:
        - /operation
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
  project: default
  sources:
    - repoURL: 'https://github.com/ThomasHelmCharts/argocd-applications'
      path: ./
      targetRevision: "HEAD" 
      helm:
        valueFiles:
          - values.yaml
          - $templates/homepage/homepage.yaml
          - $templates/kube-ops-view/kube-ops-view.yaml
          - $templates/metrics-server/metrics-server.yaml
          - $templates/netdata/netdata.yaml
          - $templates/kubescape/kubescape.yaml
          - $templates/jupyterhub/jupyterhub.yaml
          #- $templates/coredns/coredns.yaml
          - $templates/local-path-provisioner/local-path-provisioner.yaml
          - $templates/bind9/bind9.yaml
          - $values/bind9.yaml
          - $templates/nginx/nginx-ds-nodePort.yaml          
        valuesObject:
          apps_dict_tpl:
            github.com/ThomasInfras/argocd-template/nginx/nginx-ds-nodePort:
              nginx:
                spec:
                  source:
                    helm:
                      valuesObject:                                                                                                                                                                                         
                        controller:
                          config:
                            bind-address: 192.168.1.136
          domain: &domain .talos
          apps_values:
            git@github.com/ThomasInfras/argocd-template/homepage/homepage:
              domain: *domain
            git@github.com/ThomasInfras/argocd-template/kube-ops-view/kube-ops-view:
              domain: *domain
            github.com/ThomasInfras/argocd-template/netdata/netdata:
              domain: *domain              
    - repoURL: 'https://github.com/ThomasInfras/argocd-templates'
      targetRevision: "HEAD"
      ref: templates
    - repoURL: 'https://github.com/ThomasInfras/k8s-automated-nuc'
      targetRevision: "HEAD"
      ref: values
