apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: main.yaml
  namespace: argocd-infra
spec:
  ignoreDifferences:
    - group: argoproj.io
      kind: Application
      jsonPointers:
        - /operation
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: argocd-infra
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
  project: default
  sources:
    - repoURL: 'https://github.com/ThomasHelmCharts/argocd-applications'
      path: ./
      targetRevision: "HEAD" 
      helm:
        valueFiles:
          - values.yaml
          # ARGOCD
          - $templates/argocd/argocd-simple.yaml
          - $templates/argocd/argocd-lookup.yaml
          - $templates/argocd/argocd-apps.yaml
          # NGINX
          #- $templates/nginx/nginx-kind.yaml
        valuesObject:
          domain: &domain .kind
          apps_values:
            git@github.com/ThomasInfras/argocd-template/argocd/argocd-simple:
              domain: *domain
            git@github.com/ThomasInfras/argocd-template/argocd/argocd-apps:
              repo: 'https://github.com/ThomasInfras/k8s-automated-kind'
      - repoURL: 'https://github.com/ThomasInfras/argocd-templates'
        targetRevision: "HEAD"
        ref: templates
